In [207]:
import librosa
import numpy as np

In [208]:
y, sr = librosa.load('/home/anton/Documents/test/1/1904.wav', sr=16000)

In [209]:
sr

16000

In [210]:
y

array([0.        , 0.        , 0.        , ..., 0.00552368, 0.00274658,
       0.00241089], dtype=float32)

In [211]:
len(y)

80000

In [212]:
n_fft = 1024
hop_length = 128
win_length = n_fft
n_mels = 128
fmin = 0.0
fmax = sr / 2

In [213]:
window = librosa.spectrum.get_window(window="hann", Nx=win_length)

In [214]:
window

array([0.00000000e+00, 9.41235870e-06, 3.76490804e-05, ...,
       8.47091021e-05, 3.76490804e-05, 9.41235870e-06])

In [215]:
len(window)

1024

In [216]:
padded_window = librosa.util.pad_center(window, n_fft)

In [217]:
padded_window

array([0.00000000e+00, 9.41235870e-06, 3.76490804e-05, ...,
       8.47091021e-05, 3.76490804e-05, 9.41235870e-06])

In [218]:
len(padded_window)

1024

In [219]:
reflected_signal = np.pad(y, int(n_fft / 2), 'reflect')

In [220]:
reflected_signal

array([ 0.        ,  0.        ,  0.        , ...,  0.00256348,
       -0.00308228,  0.00222778], dtype=float32)

In [221]:
len(reflected_signal)

81024

In [222]:
frames = librosa.util.frame(reflected_signal, n_fft, hop_length)

In [223]:
frames

array([[ 0.        ,  0.        ,  0.        , ..., -0.00231934,
         0.00241089, -0.00308228],
       [ 0.        ,  0.        ,  0.        , ...,  0.0010376 ,
         0.00115967,  0.00256348],
       [ 0.        ,  0.        ,  0.        , ..., -0.00067139,
        -0.00265503,  0.00112915],
       ...,
       [ 0.        ,  0.        , -0.00180054, ..., -0.00460815,
        -0.00265503,  0.00256348],
       [ 0.        ,  0.        , -0.00271606, ..., -0.00073242,
         0.00076294, -0.00308228],
       [ 0.        ,  0.        , -0.00354004, ..., -0.0010376 ,
         0.00326538,  0.00222778]], dtype=float32)

In [224]:
frames.shape

(1024, 626)

In [245]:
s = librosa.spectrum._spectrogram(y=y, n_fft=n_fft, hop_length=hop_length)

In [246]:
s

(array([[0.0000000e+00, 0.0000000e+00, 7.1481132e-05, ..., 2.9961243e-02,
         7.4929558e-03, 4.4378587e-03],
        [0.0000000e+00, 0.0000000e+00, 1.6024116e-04, ..., 6.4963527e-02,
         6.0226049e-02, 5.2939437e-02],
        [0.0000000e+00, 0.0000000e+00, 2.9443973e-04, ..., 5.9920043e-02,
         9.5473275e-02, 1.0970184e-01],
        ...,
        [0.0000000e+00, 0.0000000e+00, 2.8834745e-04, ..., 3.7044156e-02,
         2.0784175e-02, 1.4448662e-02],
        [0.0000000e+00, 0.0000000e+00, 2.6805163e-04, ..., 2.7901538e-02,
         1.3607569e-02, 3.6826918e-03],
        [0.0000000e+00, 0.0000000e+00, 2.6066307e-04, ..., 9.3097733e-03,
         7.7705407e-03, 1.5587138e-02]], dtype=float32), 1024)

In [247]:
s.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
fft_freq = librosa.time_frequency.fft_frequencies(sr=sr, n_fft=n_fft)

In [ ]:
fft_freq

In [ ]:
len(fft_freq)

In [ ]:
mel_freq = librosa.time_frequency.mel_frequencies(n_mels=n_mels+2, fmin=0, fmax=sr/2)

In [ ]:
mel_freq

In [ ]:
len(mel_freq)

In [ ]:
fdiff = np.diff(mel_freq)

In [ ]:
fdiff

In [229]:
len(fdiff)

129

In [230]:
ramps = np.subtract.outer(mel_freq, fft_freq)

In [231]:
ramps

array([[ 0.00000000e+00, -1.56250000e+01, -3.12500000e+01, ...,
        -7.96875000e+03, -7.98437500e+03, -8.00000000e+03],
       [ 2.33827599e+01,  7.75775993e+00, -7.86724007e+00, ...,
        -7.94536724e+03, -7.96099224e+03, -7.97661724e+03],
       [ 4.67655199e+01,  3.11405199e+01,  1.55155199e+01, ...,
        -7.92198448e+03, -7.93760948e+03, -7.95323448e+03],
       ...,
       [ 7.62333054e+03,  7.60770554e+03,  7.59208054e+03, ...,
        -3.45419464e+02, -3.61044464e+02, -3.76669464e+02],
       [ 7.80939462e+03,  7.79376962e+03,  7.77814462e+03, ...,
        -1.59355382e+02, -1.74980382e+02, -1.90605382e+02],
       [ 8.00000000e+03,  7.98437500e+03,  7.96875000e+03, ...,
         3.12500000e+01,  1.56250000e+01, -1.81898940e-12]])

In [232]:
ramps.shape

(130, 513)

In [233]:
mels = librosa.filters.mel(sr=sr, n_fft=n_fft)

In [234]:
mels

array([[0.        , 0.02857778, 0.02837754, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01438901, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00087053, 0.00043527,
        0.        ]], dtype=float32)

In [235]:
mels.shape

(128, 513)

In [238]:
s

array([[0.0000000e+00, 0.0000000e+00, 7.1481132e-05, ..., 2.9961243e-02,
        7.4929558e-03, 4.4378587e-03],
       [0.0000000e+00, 0.0000000e+00, 1.6024116e-04, ..., 6.4963527e-02,
        6.0226049e-02, 5.2939437e-02],
       [0.0000000e+00, 0.0000000e+00, 2.9443973e-04, ..., 5.9920043e-02,
        9.5473275e-02, 1.0970184e-01],
       ...,
       [0.0000000e+00, 0.0000000e+00, 2.8834745e-04, ..., 3.7044156e-02,
        2.0784175e-02, 1.4448662e-02],
       [0.0000000e+00, 0.0000000e+00, 2.6805163e-04, ..., 2.7901538e-02,
        1.3607569e-02, 3.6826918e-03],
       [0.0000000e+00, 0.0000000e+00, 2.6066307e-04, ..., 9.3097733e-03,
        7.7705407e-03, 1.5587138e-02]], dtype=float32)

In [239]:
s.shape

(513, 626)

In [240]:
mel_s = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=n_fft, hop_length=hop_length)

In [241]:
mel_s

array([[0.0000000e+00, 0.0000000e+00, 3.1939824e-09, ..., 2.2249272e-04,
        3.6232211e-04, 4.2160100e-04],
       [0.0000000e+00, 0.0000000e+00, 1.3651618e-08, ..., 3.1058220e-04,
        4.1253306e-04, 4.4648859e-04],
       [0.0000000e+00, 0.0000000e+00, 2.2923901e-08, ..., 1.6169845e-04,
        2.1119256e-04, 2.2138086e-04],
       ...,
       [0.0000000e+00, 0.0000000e+00, 5.2162110e-09, ..., 3.8277576e-05,
        3.4485678e-05, 3.0898900e-05],
       [0.0000000e+00, 0.0000000e+00, 1.2398743e-08, ..., 7.4972108e-05,
        6.9234178e-05, 6.5050255e-05],
       [0.0000000e+00, 0.0000000e+00, 1.4535673e-08, ..., 8.7450309e-05,
        6.9726113e-05, 6.0089686e-05]], dtype=float32)

In [242]:
mel_s.shape

(128, 626)

In [303]:
def melspectrogram(y=None, sr=22050, S=None, n_fft=2048, hop_length=512,
                   win_length=None, window='hann', center=True, pad_mode='reflect',
                   power=2.0, **kwargs):

    S, n_fft = librosa.spectrum._spectrogram(y=y, S=S, n_fft=n_fft, hop_length=hop_length, power=power,
                            win_length=win_length, window=window, center=center,
                            pad_mode=pad_mode)
#     print(S[0])

    # Build a Mel filter
    mel_basis = librosa.filters.mel(sr, n_fft, **kwargs)
    print(mel_basis[0][2])
    print(S[0][2])
    

    print(mel_basis)
    print(S)
    
    
    return np.dot(mel_basis, S)

In [304]:
melspectrogram(y=y, sr=sr, n_fft=n_fft, hop_length=hop_length)

0.028377542
5.1095523e-09
[[0.         0.02857778 0.02837754 ... 0.         0.         0.        ]
 [0.         0.         0.01438901 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.00087053 0.00043527 0.        ]]
[[0.00000000e+00 0.00000000e+00 5.10955234e-09 ... 8.97676102e-04
  5.61443849e-05 1.96945894e-05]
 [0.00000000e+00 0.00000000e+00 2.56772310e-08 ... 4.22025984e-03
  3.62717710e-03 2.80258409e-03]
 [0.00000000e+00 0.00000000e+00 8.66947545e-08 ... 3.59041151e-03
  9.11514647e-03 1.20344944e-02]
 ...
 [0.00000000e+00 0.00000000e+00 8.31442506e-08 ... 1.37226947e-03
  4.31981927e-04 2.08763842e-04]
 [0.00000000e+00 0.00000000e+00 7.18516802e-08 ... 7.78495800e-04
  1.85165933e-04 1.35622195e-05]
 [0.00000000e+00 0.00000000e+0

array([[0.0000000e+00, 0.0000000e+00, 3.1939824e-09, ..., 2.2249272e-04,
        3.6232211e-04, 4.2160100e-04],
       [0.0000000e+00, 0.0000000e+00, 1.3651618e-08, ..., 3.1058220e-04,
        4.1253306e-04, 4.4648859e-04],
       [0.0000000e+00, 0.0000000e+00, 2.2923901e-08, ..., 1.6169845e-04,
        2.1119256e-04, 2.2138086e-04],
       ...,
       [0.0000000e+00, 0.0000000e+00, 5.2162110e-09, ..., 3.8277576e-05,
        3.4485678e-05, 3.0898900e-05],
       [0.0000000e+00, 0.0000000e+00, 1.2398743e-08, ..., 7.4972108e-05,
        6.9234178e-05, 6.5050255e-05],
       [0.0000000e+00, 0.0000000e+00, 1.4535673e-08, ..., 8.7450309e-05,
        6.9726113e-05, 6.0089686e-05]], dtype=float32)

In [308]:
np.abs(np.fft.rfft([0.0004567, 0.988625, 98.00098532, 4.982356, -0.0023461, -43, 1.00035277, -0.1]))

array([ 61.87042969, 134.54235189, 109.54752877,  68.10477177,
       136.12846769])

In [309]:
np.fft.rfft([0.0004567, 0.988625, 98.00098532, 4.982356, -0.0023461, -43, 1.00035277, -0.1])

array([ 61.87042969  +0.j        ,  27.51368944-131.69905597j,
       -99.00322749 +46.893731j  , -27.50808384 +62.30220913j,
       136.12846769  +0.j        ])

In [2]:
from keras.models import load_model
from keras import backend as K
from tensorflow.python.framework.graph_util import convert_variables_to_constants
import tensorflow as tf

In [3]:
keras_model_path = '/home/anton/ITS_Partner_Lab/its_partnet_lab/1_1.h5'
wkdir = '/home/anton/ITS_Partner_Lab/its_partnet_lab/'
pb_filename = '1_1.pb'

In [12]:
K.set_learning_phase(0)

In [4]:
model = load_model(keras_model_path)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



In [10]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input (InputLayer)              (None, 128, 126)     0                                            
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 128, 126, 1)  0           input[0][0]                      
__________________________________________________________________________________________________
permute_1 (Permute)             (None, 126, 128, 1)  0           reshape_1[0][0]                  
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 126, 128, 10) 60          permute_1[0][0]                  
____________________________________________________________________________________________

In [14]:
estimator_model = tf.keras.estimator.model_to_estimator(keras_model = model, model_dir = wkdir)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using the Keras model provided.


ValueError: Fetch argument <tf.Variable 'conv2d_1/kernel:0' shape=(5, 1, 1, 10) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("conv2d_1/kernel/Read/ReadVariableOp:0", shape=(5, 1, 1, 10), dtype=float32) is not an element of this graph.)